apiVersion: v1
kind: ServiceAccount
metadata:
  name: medicine-inventory-sa
  namespace: tom-wakhungu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: medicine-inventory-role
  namespace: tom-wakhungu
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: medicine-inventory-rolebinding
  namespace: tom-wakhungu
subjects:
- kind: ServiceAccount
  name: medicine-inventory-sa
  namespace: tom-wakhungu
roleRef:
  kind: Role
  name: medicine-inventory-role
  apiGroup: rbac.authorization.k8s.io